const DAYS = [
  { day: "Mon", type: "Strength A", detail: "RDL · Lunge · Squat", variant: "default" },
  { day: "Tue", type: "Threshold", detail: "4×6min @ 5:12/km", variant: "default" },
  { day: "Wed", type: "Rest", detail: null, variant: "rest" },
  { day: "Thu", type: "Hybrid", detail: "30 wb + 400m × 3", variant: "hybrid" },
  { day: "Fri", type: "Easy run", detail: "50 min @ 6:00/km", variant: "default" },
  { day: "Sat", type: "Strength B", detail: "Press · Row · Carry", variant: "default" },
  { day: "Sun", type: "Rest", detail: null, variant: "rest" },
] as const;

export function SamplePlan() {
  return (
    <section className="mx-auto w-full max-w-5xl px-4 py-16">
      <div className="mb-6 flex flex-col gap-1.5">
        <h2 style={{ fontSize: "17px", fontWeight: 500 }}>
          What your plan actually looks like.
        </h2>
        <p className="text-[13px] text-muted-foreground">
          One week from a 14-week sub-1:30 plan. Generated by Coach — not a template.
        </p>
      </div>

      {/* 7-day grid — horizontal scroll on mobile */}
      <div className="mb-4 overflow-x-auto">
        <div className="grid min-w-[560px] grid-cols-7 gap-2">
          {DAYS.map(({ day, type, detail, variant }) => (
            <div
              key={day}
              className={[
                "flex flex-col gap-1 rounded-lg p-3",
                variant === "hybrid"
                  ? "bg-[#534AB7] text-white"
                  : variant === "rest"
                    ? "bg-muted text-muted-foreground"
                    : "border bg-background",
              ].join(" ")}
            >
              <span
                className={[
                  "text-[9px] font-semibold uppercase tracking-widest",
                  variant === "hybrid" ? "opacity-70" : "text-muted-foreground",
                ].join(" ")}
              >
                {day}
              </span>
              <span className="text-[12px] font-medium leading-tight">{type}</span>
              {detail && (
                <span
                  className={[
                    "text-[11px] leading-snug",
                    variant === "hybrid" ? "opacity-80" : "text-muted-foreground",
                  ].join(" ")}
                >
                  {detail}
                </span>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Coach quote callout */}
      <div className="border-l-2 border-foreground bg-secondary px-[14px] py-[10px]">
        <p className="mb-1 text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">
          Coach (Honest)
        </p>
        <p className="text-[13px] leading-snug">
          &ldquo;Hybrid sessions start this week. They are unpleasant. That&apos;s the work.&rdquo;
        </p>
      </div>
    </section>
  );
}
